// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface TaxaSearch {
    total_results: number;
    page:          number;
    per_page:      number;
    results:       Result[];
}

export interface Result {
    id:                    number;
    iconic_taxon_id:       number;
    iconic_taxon_name:     string;
    is_active:             boolean;
    name:                  string;
    preferred_common_name: string;
    rank:                  string;
    rank_level:            number;
    default_photo:         DefaultPhoto;
    matched_term:          string;
    observations_count:    number;
}

export interface DefaultPhoto {
    id:           number;
    attribution:  string;
    license_code: string;
    url:          string;
    medium_url:   string;
    square_url:   string;
}